package vista;

import clases.Combinacion;
import clases.Configuracion;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConfiguracionDAO;

/**
 *
 * @author PC
 */
public class Ajustes extends javax.swing.JFrame {

    private int var;
    private DefaultTableModel modelo = new DefaultTableModel();
    private Combinacion c = new Combinacion();
    private Configuracion cf = new Configuracion();
    private ConfiguracionDAO cd = new ConfiguracionDAO();

    public Ajustes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void cargarTabla(int dificultad) {

        modelo = (DefaultTableModel) tablaCombinaciones.getModel();
        List<Combinacion> lp = cd.listarCombinaciones(dificultad);
        for (Combinacion p : lp) {
            modelo.addRow(new Object[]{p.getId(), p.getCombinacion(), p.getPlayer()});
        }
        this.tablaCombinaciones.setModel(modelo);

    }

    public void limpiarTabla(DefaultTableModel model) {
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setRowCount(0);
        }
    }

    private void mostrarConfiguraciones(int id) {
        Configuracion c = cd.listarConfiguraciones(id);
        this.txtTiempo.setText(String.valueOf(c.getTiempo()));
        this.txtPuntos_Tiempo.setText(String.valueOf(c.getPunto_Tiempo()));
        this.txtPuntos_Acierto.setText(String.valueOf(c.getPunto_Acierto()));
    }

    private void limpiar(int id) {
        this.lbl_ID.setText(String.valueOf(id));
        this.lbl_IDComb.setText("");
        this.txtCombinacion.setText("");
        mostrarConfiguraciones(id);
        limpiarTabla(modelo);
        cargarTabla(id);
    }

    private void limipar2(int id) {

        this.lbl_IDComb.setText("");
        this.txtCombinacion.setText("");
        limpiarTabla(modelo);
        cargarTabla(id);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDificil = new javax.swing.JButton();
        btnFacil = new javax.swing.JButton();
        btnMedio1 = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lbl_ID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelColor = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCombinaciones = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        txtPuntos_Tiempo = new javax.swing.JTextField();
        txtPuntos_Acierto = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtCombinacion = new javax.swing.JTextField();
        player2 = new javax.swing.JRadioButton();
        player1 = new javax.swing.JRadioButton();
        btnEliminarComb = new javax.swing.JButton();
        btnAgregarComb = new javax.swing.JButton();
        lbl_IDComb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(710, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDificil.setBackground(new java.awt.Color(255, 51, 51));
        btnDificil.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnDificil.setForeground(new java.awt.Color(0, 0, 0));
        btnDificil.setText("DIFICIL");
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        jPanel2.add(btnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 145, 47));

        btnFacil.setBackground(new java.awt.Color(51, 255, 51));
        btnFacil.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnFacil.setForeground(new java.awt.Color(0, 0, 0));
        btnFacil.setText("FACIL");
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        jPanel2.add(btnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 145, 47));

        btnMedio1.setBackground(new java.awt.Color(255, 255, 51));
        btnMedio1.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnMedio1.setForeground(new java.awt.Color(0, 0, 0));
        btnMedio1.setText("MEDIO");
        btnMedio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedio1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMedio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 145, 47));

        btnInicio.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio_48.png"))); // NOI18N
        btnInicio.setText("INICIO");
        btnInicio.setBorder(null);
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 60));
        jPanel2.add(lbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 200, 450));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ajustes_48_b.png"))); // NOI18N
        jLabel1.setText("AJUSTES");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 50));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelColor.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel32.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("COMBINACION:");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 30));

        tablaCombinaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "COMBINACION", "PLAYER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCombinaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCombinacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCombinaciones);
        if (tablaCombinaciones.getColumnModel().getColumnCount() > 0) {
            tablaCombinaciones.getColumnModel().getColumn(0).setMinWidth(50);
            tablaCombinaciones.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaCombinaciones.getColumnModel().getColumn(0).setMaxWidth(50);
            tablaCombinaciones.getColumnModel().getColumn(1).setPreferredWidth(250);
            tablaCombinaciones.getColumnModel().getColumn(2).setMinWidth(75);
            tablaCombinaciones.getColumnModel().getColumn(2).setPreferredWidth(75);
            tablaCombinaciones.getColumnModel().getColumn(2).setMaxWidth(75);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 440, 130));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Seg.");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 30));

        jLabel35.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("PUNTOS X TIEMPO:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 38, -1, 30));

        jLabel34.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("PUNTOS X ACIERTO:");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 38, 140, 30));

        txtTiempo.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jPanel5.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, -1));

        txtPuntos_Tiempo.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jPanel5.add(txtPuntos_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, -1));

        txtPuntos_Acierto.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jPanel5.add(txtPuntos_Acierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 80, -1));

        jLabel36.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("TIEMPO:");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(204, 255, 255), null, null));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel5.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, 130));

        txtCombinacion.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jPanel4.add(txtCombinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 330, -1));

        buttonGroup1.add(player2);
        player2.setText("PLAYER 2");
        jPanel4.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        buttonGroup1.add(player1);
        player1.setText("PLAYER 1");
        jPanel4.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        btnEliminarComb.setBackground(new java.awt.Color(204, 255, 204));
        btnEliminarComb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEliminarComb.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarComb.setText("ELIMINAR");
        btnEliminarComb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(204, 255, 255), null, null));
        btnEliminarComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCombActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 110, 30));

        btnAgregarComb.setBackground(new java.awt.Color(204, 255, 204));
        btnAgregarComb.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregarComb.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarComb.setText("AGREGAR");
        btnAgregarComb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(204, 255, 255), null, null));
        btnAgregarComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCombActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, 30));

        lbl_IDComb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lbl_IDComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 40, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 500, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed

        limpiar(3);

    }//GEN-LAST:event_btnDificilActionPerformed

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed

        limpiar(1);

    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnMedio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedio1ActionPerformed

        limpiar(2);
    }//GEN-LAST:event_btnMedio1ActionPerformed

    private void btnEliminarCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCombActionPerformed

        if (this.lbl_IDComb.getText() != "") {
            int dificultad = Integer.valueOf(this.lbl_IDComb.getText());

            int des = JOptionPane.showConfirmDialog(this, "Esta seguro de que desea eliminar este registro");
            if (des == 0) {
                if (cd.eliminarCombinacion(dificultad)) {
                    JOptionPane.showMessageDialog(this, "Se Elimino");
                    limipar2(dificultad);
                } else {
                    JOptionPane.showMessageDialog(this, "No se elmino");
                }
            }

        }
    }//GEN-LAST:event_btnEliminarCombActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (this.txtTiempo.getText() != "" && this.txtPuntos_Tiempo.getText() != "" && this.txtPuntos_Acierto.getText() != "") {
            int tiempo = Integer.parseInt(this.txtTiempo.getText());
            int puntos_tiempo = Integer.parseInt(this.txtPuntos_Tiempo.getText());
            int puntos_acierto = Integer.parseInt(this.txtPuntos_Acierto.getText());
            int id = Integer.parseInt(this.lbl_ID.getText());

            cf = new Configuracion(id, tiempo, puntos_tiempo, puntos_acierto);
            if (cd.guardarConfiguracion(cf)) {
                JOptionPane.showMessageDialog(this, "Se guardo");
                mostrarConfiguraciones(id);
            } else {
                JOptionPane.showMessageDialog(this, "No se Guardo");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCombActionPerformed
        if (this.lbl_ID.getText() != "") {
            if (this.txtCombinacion.getText() != "") {
                ButtonModel seleccion = buttonGroup1.getSelection();
                if (seleccion != null) {
                    int dificultad = Integer.valueOf(this.lbl_ID.getText());
                    String combinacion = this.txtCombinacion.getText();
                    if (this.player1.isSelected()) {
                        c = new Combinacion(combinacion, 1, dificultad);

                    } else if (this.player2.isSelected()) {
                        c = new Combinacion(combinacion, 2, dificultad);
                    }
                    if (cd.agregarCombinacion(c)) {
                        JOptionPane.showMessageDialog(this, "Se Agrego");
                        limipar2(dificultad);

                    } else {
                        JOptionPane.showMessageDialog(this, "No Se Agrego");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione un Jugador");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Llene todos los campos");
            }
        }

    }//GEN-LAST:event_btnAgregarCombActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

        Inicio i = new Inicio();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void tablaCombinacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCombinacionesMouseClicked
        int fila = this.tablaCombinaciones.rowAtPoint(evt.getPoint());
        this.lbl_IDComb.setText(this.tablaCombinaciones.getValueAt(fila, 0).toString());
        this.txtCombinacion.setText(this.tablaCombinaciones.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_tablaCombinacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajustes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComb;
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnEliminarComb;
    private javax.swing.JButton btnFacil;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMedio1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_IDComb;
    private javax.swing.JPanel panelColor;
    private javax.swing.JRadioButton player1;
    private javax.swing.JRadioButton player2;
    private javax.swing.JTable tablaCombinaciones;
    private javax.swing.JTextField txtCombinacion;
    private javax.swing.JTextField txtPuntos_Acierto;
    private javax.swing.JTextField txtPuntos_Tiempo;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
